[package]
name = "auth-actix-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
actix-web = "4.9.0"
base64 = "0.22.1"
auth-core = { path = "../../core" }
auth-dal = { path = "../../dal" }
glue = { path = "../../../../glue", features = ["actix"] }
# kernel feature must be the same as the to-do-actix-server
# when compiling both servers into ingress to avoid conflicts.
# For independent actix-server deployments the kernel feature can be different.
auth-kernel = { path = "../../kernel", features = ["core-postgres"] }
