[package]
name = "auth-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
auth-core = { path = "../core", optional = true }
auth-dal = { path = "../dal" }
glue = { path = "../../../glue" }
reqwest = {version = "0.12.5", optional = true, features = ["json"]}
dotenv = { version = "0.15" , optional = true}

[features]
http = ["reqwest", "dotenv"]
core-postgres = ["auth-core"]