[package]
name = "to-do-dal"
version = "0.1.0"
edition = "2024"

[dependencies]
serde ={ version="1.0.197", features = ["derive"] }
glue = { path = "../../../glue"}
# for json-file
serde_json ={ version="1.0.114", optional = true }
# for sqlx-postgres
sqlx = { version = "0.8.3", features = ["runtime-tokio-rustls", "tls-rustls", "migrate", "postgres", "json"], optional = true }
dotenv = { version = "0.15", optional = true }

[features]
json-file = ["serde_json"]
sqlx-postgres = ["sqlx", "dotenv"]
