[package]
name = "glue"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { version = "4.9.0", optional = true } # optional=true -> only used if the actix feature is enabled
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
futures = "0.3.30"
jsonwebtoken = "9.3.1"
dotenv = { version = "0.15"}

[features]
actix = ["actix-web"]
